#!/usr/bin/sh

[ -z "$DMENU" ] && DMENU="dmenu"

swallowed="/tmp/swallowed_$USER"
hidden="/tmp/hidden_$USER"

# Get class of a wid
get_class() {
    id=$1
    if [ -z "$id" ]; then
        echo ""
    else
        xprop -id "$id" | sed -n \
            -e '/WM_CLASS/s/\( "\)/\n/g; s/[^\n]*\n\([^"]*\)[^\n]*/\1\n/g' \
            -e '/WM_COMMAND/s/[^"]*/\n\n/1; s/\n"//1; s/\n\([^"]*\)".*/\n\1/; /\n/p' | sed '/^$/d' | head -n1
    fi
}

get_name() {
    xprop WM_NAME -id "$1" | sed 's/^[^"]*"\(.*\)"$/\1/'
}

get_pid() {
    xprop _NET_WM_PID -id "$1" | awk '/[0-9]+/ {print $3}'
}

get_ppid() {
    ps -o ppid= -p $1
}

check_swallowing_process() {
    pid=$(get_pid $1)
    [ -z $pid ] && return 0
    gppid=$(get_ppid $(get_ppid $pid))
    grep -i "^$(ps -o cmd= -p $gppid | awk '{print $1}' | sed 's_^.*/__')$" ~/.config/bspwm/terminals && return 0
    [ "$(get_ppid "$(get_ppid "$(get_pid "$1")")")" = "$(get_pid "$2")" ] && return 0 || return 1
}

hide() {
    [ -z "$1" ] && id=$(bspc query -N -n) || id=$1
    bspc node "$id" --flag hidden=on
    echo "$id" >>$hidden
    [ $# -ge 2 ] && echo "$2 $1" >>$swallowed
}

show() {
    [ -z "$1" ] && return
    bspc node "$1" --flag hidden=off
    d=$(bspc query -D -n "$1")
    [ $# -ge 2 ] && [ "$d" = "$2" ] || bspc node "$1" -d "$2"
    bspc node "$1" -f
    sed -i "/$1/d" $hidden
    sed -i "/$1/d" $swallowed
}

sel() {
    ids=$(tac $hidden)
    wins=$(for id in $ids; do [ ! -z "$id" ] && echo "$id: \"$(get_name $id)\" ($(</proc/$(get_pid $id)/comm))"; done)
    search=$($DMENU -p show <<< "$wins")
    [ -z "$search" ] && return
    show ${search%%:*}
}

swallow() {
    addedtodesktop=$2
    lasttermdesktop=$(bspc query -D -n last)

    swallowerid=$1
    swallowingid=$(bspc query -N -n last)
    if [ "$addedtodesktop" = "$lasttermdesktop" ] && check_swallowing_process "$swallowerid" "$swallowingid"; then
        grep -q "^$(get_class "$swallowerid")$" ~/.config/bspwm/noswallow && return
        grep -i "^$(get_class "$swallowingid")$" ~/.config/bspwm/terminals || return
        hide "$swallowingid" "$swallowerid"
    fi
}

spit() {
    spitterid=$1
    spitterdesktop=$2
    grep "^$spitterid" $swallowed || return
    spittingid=$(grep "^$spitterid" $swallowed | head -n1 | awk '{print $2}')

    show $spittingid $spitterdesktop
}

run() {
    bspc subscribe node_add node_remove | while read -r event; do
        case $(echo "$event" | awk '{ print $1 }') in
        node_add)
            swallow $(echo "$event" | awk '{print $5 " " $3}')
            ;;
        node_remove)
            spit $(echo "$event" | awk '{print $4 " " $3}')
            ;;
        esac
    done
}

[ $# -eq 0 ] || [ "$1" = "run" ] && run
[ "$1" = "hide" ] && hide $2
[ "$1" = "show" ] && show $2
[ "$1" = "select" ] && sel
